### ISSUE TITLE
attempt to index local 'affix' (a nil value)

### ISSUE THREAD

**Issue by yoshimo** [BloodDragon2580/MythicPlusDrop#1]
1x MythicPlusDrop/module/Schedule.lua:167: attempt to index local 'affix' (a nil value)
[string "@MythicPlusDrop/module/Schedule.lua"]:167: in function <MythicPlusDrop/module/Schedule.lua:134>
[string "=[C]"]: in function `Update'
[string "@Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua"]:116: in function <...dOns/Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua:107>

Locals:
weeklyChest = Frame {
 Highlight = Texture {
 }

**Comment by BloodDragon2580** [comment]
I have no gametime at this moment, can you test this version pls:
[MythicPlusDrop.zip](https://github.com/user-attachments/files/17083592/MythicPlusDrop.zip)

**Comment by BloodDragon2580** [comment]
Here is a other version for testing:
[MythicPlusDrop.zip](https://github.com/user-attachments/files/17085023/MythicPlusDrop.zip)

**Comment by yoshimo** [comment]
I tried both and for now no lua error appears.
Neither does the debug line you added

**Comment by BloodDragon2580** [comment]
Ok I'll upload the version to curseforge tomorrow, but without debug output. Thx for testing the files.
